name: Generate deb file

on:
  push:
    branches: 
    - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Install Build-Depends and generate deb file
      run: |
        sudo apt update
        sudo apt -y install devscripts debhelper dh-sequence-dkms
        debuild -i -us -uc -b
