name: Generate deb file

on:
  push:
    branches: 
    - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./.github/docker/
          platforms: linux/amd64
          push: false
          tags: debian-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Try images
        run: |
          docker images
          docker run debian-build:latest /bin/bash -c "echo TEST"
          ls -la
          pwd
          env
